name: API Testing Framework

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
permissions:
  contents: read
  checks: write
jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: API_SOM/DemoApiTesting

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17  
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Execute TestNG Tests
      run: mvn clean test -Dsurefire.suiteXmlFiles=testng.xml

    - name: Upload Test Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-artifacts
        path: API_SOM/DemoApiTesting/logs/

    - name: Publish Test Report
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: TestNG Results
        path: API_SOM/DemoApiTesting/test-output/junitreports/TEST-*.xml
        reporter: java-junit
